### ISSUE TITLE
variable for colors

### ISSUE THREAD

**Issue by juanlramos** [ashforreal192/Responsive-Landing-Page#1]
Nice landing page, i was analizing your code and i saw that you used the name of all color and hexadeciamal code in every elements, it would be better if you have used variable for colors, it's better for maintenance. i'm studying how to contribute with another developer, i can fix it for you if you want.

**Comment by ashforreal192** [comment]
I haven't really used variables in the past but sure go ahead, I'm open to seeing what it's like

**Comment by juanlramos** [comment]
i've just done the pull request with the new version of the code, with variables. if you've never used you should, it's really easier to change colors with big codes, you can change every color just changind the variable values, thanks for letting me help :)
